services:
  playwright-agent:
    container_name: playwright-agent
    build:
      context: .
      dockerfile: docker/Dockerfile   # <-- פה הדוקרפייל שלך
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MAX_COMPLETION_TOKENS: ${OPENAI_MAX_COMPLETION_TOKENS:-1536}
      OPENAI_MODEL_ANALYZER: ${OPENAI_MODEL_ANALYZER:-gpt-5-mini}
      OPENAI_MODEL_ENFORCER: ${OPENAI_MODEL_ENFORCER:-gpt-5-mini}
      OPENAI_MODEL_BUILDER: ${OPENAI_MODEL_BUILDER:-gpt-5}
      OPENAI_FORCE_JSON: ${OPENAI_FORCE_JSON:-1}
    working_dir: /app
    volumes:
      - .:/app
    shm_size: "2gb"
    extra_hosts:
      - "host.docker.internal:host-gateway"
