version: "3"

services:
  playwright-agent:
    container_name: playwright_agent
    build:
      context: .
      dockerfile: docker/Dockerfile
    network_mode: "host"
    volumes:
      - ./tests:/app/tests          # Persist generated tests
    environment:
      - LLM_URL=http://192.168.20.31:1234/v1/chat/completions
      - HEADFUL=0                   # Flip to 1 for visible browser
    stdin_open: true
    tty: true
  